# Generated by Django 5.1.4 on 2024-12-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendee",
            name="events",
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("booked", "Booked"), ("canceled", "Canceled")],
                default="booked",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendee",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
