# Generated by Django 5.1.4 on 2024-12-19 08:42

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_options_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="events",
            field=models.ManyToManyField(through="events.Ticket", to="events.event"),
        ),
        migrations.AddField(
            model_name="attendee",
            name="user",
            field=models.OneToOneField(
                default=events.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizer",
            name="user",
            field=models.OneToOneField(
                default=events.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
